#ifndef CDATAPROVIDERMANAGER_GLOBAL_H
#define CDATAPROVIDERMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef CDATAPROVIDERMANAGER_LIB
# define CDATAPROVIDERMANAGER_EXPORT Q_DECL_EXPORT
#else
# define CDATAPROVIDERMANAGER_EXPORT Q_DECL_IMPORT
#endif

#endif // CDATAPROVIDERMANAGER_GLOBAL_H
