#ifndef EARTHQUAKEDATAPROVIDER_GLOBAL_H
#define EARTHQUAKEDATAPROVIDER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifndef EARTHQUAKEDATAPROVIDER_LIB
# define EARTHQUAKEDATAPROVIDER_EXPORT Q_DECL_EXPORT 
#else
# define EARTHQUAKEDATAPROVIDER_EXPORT Q_DECL_IMPORT
#endif

#endif // EARTHQUAKEDATAPROVIDER_GLOBAL_H
