#ifndef STATIONINTERPOLATION_GLOBAL_H
#define STATIONINTERPOLATION_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef STATIONINTERPOLATION_LIB
# define STATIONINTERPOLATION_EXPORT Q_DECL_EXPORT
#else
# define STATIONINTERPOLATION_EXPORT Q_DECL_IMPORT
#endif

#endif // STATIONINTERPOLATION_GLOBAL_H
