#ifndef RADARSINGLEDATAPROVIDER_GLOBAL_H
#define RADARSINGLEDATAPROVIDER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef RADARSINGLEDATAPROVIDER_LIB
# define RADARSINGLEDATAPROVIDER_EXPORT Q_DECL_EXPORT
#else
# define RADARSINGLEDATAPROVIDER_EXPORT Q_DECL_IMPORT
#endif

#endif // RADARSINGLEDATAPROVIDER_GLOBAL_H
