#ifndef RADARSTRUCTDATAPROVIDER_GLOBAL_H
#define RADARSTRUCTDATAPROVIDER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef RADARSTRUCTDATAPROVIDER_LIB
# define RADARSTRUCTDATAPROVIDER_EXPORT Q_DECL_EXPORT
#else
# define RADARSTRUCTDATAPROVIDER_EXPORT Q_DECL_IMPORT
#endif

#endif // RADARSTRUCTDATAPROVIDER_GLOBAL_H
